{
	"version": 1548202248,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/parede-sheet0.png",
		"images/parede-sheet1.png",
		"images/numeros-sheet0.png",
		"images/numeros-sheet1.png",
		"images/vida-sheet0.png",
		"images/f1-sheet0.png",
		"images/f1-sheet1.png",
		"images/f1-sheet2.png",
		"images/f1-sheet3.png",
		"images/sensor-sheet0.png",
		"images/sensor-sheet1.png",
		"images/vitoria-sheet0.png",
		"images/tutorial-sheet0.png",
		"images/chao2-sheet0.png",
		"images/opções-sheet0.png",
		"images/opções-sheet1.png",
		"images/opções-sheet2.png",
		"images/logo-sheet0.png",
		"images/barravida-sheet0.png",
		"images/barravida2-sheet0.png",
		"images/operando-sheet0.png",
		"images/sensor_operando-sheet0.png",
		"images/sensor_operando-sheet1.png",
		"images/zona-sheet0.png",
		"images/fasenodisponivel-sheet0.png",
		"images/textquebrou-sheet0.png",
		"images/album-sheet0.png",
		"images/album-sheet1.png",
		"images/album-sheet2.png",
		"images/album-sheet3.png",
		"images/chao_sensor-sheet0.png",
		"images/ceu-sheet0.png",
		"images/setas-sheet0.png",
		"images/setas-sheet1.png",
		"images/prissionadoope-sheet0.png",
		"images/prissionadonum-sheet0.png",
		"images/selomultiplicador-sheet0.png",
		"images/perça4-sheet0.png",
		"images/perça4-sheet1.png",
		"images/perça-sheet0.png",
		"images/perça-sheet1.png",
		"images/perça3-sheet0.png",
		"images/perça3-sheet1.png",
		"images/perça2-sheet0.png",
		"images/perça2-sheet1.png",
		"images/indicador-sheet0.png",
		"images/indicador-sheet1.png",
		"images/multiplicador-sheet0.png",
		"images/multiplicador-sheet1.png",
		"images/multiplicador-sheet2.png",
		"images/gamepad1-sheet0.png",
		"images/gamepad_middle-sheet0.png",
		"images/fundopause-sheet0.png",
		"images/montanhalonge.png",
		"images/montanha.png",
		"images/perça1pegar-sheet0.png",
		"images/perça2pegar-sheet0.png",
		"images/perça2pegar-sheet1.png",
		"images/chaao.png",
		"images/espadalogo-sheet0.png",
		"images/espadalogo-sheet1.png",
		"images/espadalogo-sheet2.png",
		"images/espadalogo-sheet3.png",
		"images/espadalogo-sheet4.png",
		"images/espadalogo-sheet5.png",
		"images/espadalogo-sheet6.png",
		"images/espadalogo-sheet7.png",
		"images/espadalogo-sheet8.png",
		"images/espadalogo-sheet9.png",
		"images/espadalogo-sheet10.png",
		"images/enfimlogo-sheet0.png",
		"images/enfimlogo-sheet1.png",
		"images/enfimlogo-sheet2.png",
		"images/quaselogo-sheet0.png",
		"images/quaselogo-sheet1.png",
		"images/quaselogo-sheet2.png",
		"images/lego-sheet0.png",
		"images/emp-sheet0.png",
		"images/som-sheet0.png",
		"images/som-sheet1.png",
		"images/derrotavitori-sheet0.png",
		"images/derrotavitori-sheet1.png",
		"images/grama.png",
		"images/terra.png",
		"images/sensorsom-sheet0.png",
		"images/sensoreu-sheet0.png",
		"images/cima.png",
		"images/chaoaixo.png",
		"media/Áudio fase 2 (online-audio-converter.com).ogg",
		"media/whatsapp audio 2019-01-18 at 21.37.06 (online-audio-converter.com).ogg",
		"media/fase 1 (online-audio-converter.com).m4a",
		"media/fase 1 (online-audio-converter.com).ogg",
		"media/fase 2 (online-audio-converter.com).m4a",
		"media/fase 2 (online-audio-converter.com).ogg",
		"media/fase 3 (online-audio-converter.com).m4a",
		"media/fase 3 (online-audio-converter.com).ogg",
		"media/fase 4 (online-audio-converter.com).m4a",
		"media/fase 4 (online-audio-converter.com).ogg",
		"media/menu  inicial (online-audio-converter.com).m4a",
		"media/menu  inicial (online-audio-converter.com).ogg",
		"media/menu configurações (online-audio-converter.com).m4a",
		"media/menu configurações (online-audio-converter.com).ogg",
		"media/menu tabuada (online-audio-converter.com).m4a",
		"media/menu tabuada (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}